{
  imports = [
    ./graphics
    ./development
    ./audio
    ./chromium
    ./yubikey
    ./spotify
    ./viewers
    ./discord.nix
    ./firefox.nix
    ./noi.nix
    ./obs.nix
    ./networkmanagerapplet.nix
    ./libreoffice.nix
    ./baobab.nix
    ./ledger-live-desktop.nix
  ];
}
