{
  imports = [
    ./graphics
    ./audio
    ./chromium
    ./firefox
    ./yubikey
    ./spotify
    ./viewers
    ./filesystem
    ./record
    ./terminal
    ./discord.nix
    ./noi.nix
    ./networkmanagerapplet.nix
    ./libreoffice.nix
    ./ledger-live-desktop.nix
  ];
}
