{
 "title": "Central Operations Dash - NUC",
 "description": "Inspired by A LOT of others, this is my go-to-dash.\nA collection of Node-Exporter, Cadvisor and Prometheus.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "instance",
    "query": "label_values(node_uname_info{instance=\"nuc\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu_seconds_total\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu_seconds_total, cpu)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Storage Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    }
   ]
  },
  {
   "title": "CPU Temp.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_hwmon_temp_celsius) / count(node_hwmon_temp_celsius)"
    }
   ]
  },
  {
   "title": "Swap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Cores - total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "All Cores - user",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode=\"user\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "All Cores - system",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode=\"system\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "All Cores - iowait",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "All Cores - steal",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode=\"steal\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "All Cores - other",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
      }
     ]
    },
    {
     "title": "$host - Overall CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]),1)) )),1)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{instance}}_1m" },
      { "expr": "node_load5", "legendFormat": "{{instance}}_5m" },
      { "expr": "node_load15", "legendFormat": "{{instance}}_15m" }
     ]
    },
    {
     "title": "$host - Current CPU Core Utilization",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Avg"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{instance}}_Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{instance}}_Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{instance}}_Avaliable" }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"})",
       "legendFormat": "{{instance}}：{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "description": "Read/write completions per second",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Writes completed"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_filefd_allocated", "legendFormat": "filefd_{{instance}}" },
      {
       "expr": "irate(node_context_switches_total[30m])",
       "legendFormat": "switches_{{instance}}"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_ IO time"
      }
     ]
    },
    {
     "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
     "type": "graph",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total[30m]) / irate(node_disk_reads_completed_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read time"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total[30m]) / irate(node_disk_writes_completed_total[30m])",
       "legendFormat": "{{instance}}_{{device}}_Write time"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bps", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "graph",
     "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{instance}}_CurrEstab" },
      { "expr": "node_sockstat_TCP_tw", "legendFormat": "{{instance}}_TCP_tw" },
      { "expr": "node_sockstat_sockets_used", "legendFormat": "{{instance}}_Sockets_used" },
      { "expr": "node_sockstat_UDP_inuse", "legendFormat": "{{instance}}_UDP_inuse" },
      { "expr": "node_sockstat_TCP_alloc", "legendFormat": "{{instance}}_TCP_alloc" }
     ]
    }
   ]
  },
  {
   "title": "Hardware Environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardware Temperature(VM may not display the metrics)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius",
       "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}